---
- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Install Python 3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install boto3 using pip3
  become: true
  apt:
    name: python3-boto3
    state: present

- name: Install AWS CLI using pip
  become: true
  snap:
    name: awscli --classic
    state: present

- name: Install Java JDK 17
  apt:
    name: openjdk-17-jdk
    state: present
