- name: Retrieve secret value from AWS Parameter Store
  aws_ssm:
    name: /devops-tools/jenkins/id_rsa.pub
  register: secret_value

- name: Print registered variable
  debug:
    var: secret_value

- name: Add public key to authorized_keys for ubuntu user
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ secret_value.value }}"
